<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Contact us_sale_image</name>
   <tag></tag>
   <elementGuidId>c62f4aed-70da-4f93-95fd-4b46a4c621af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='sale_image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sale_image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c1d7f64c-3fa5-4c07-aa86-bb15276829e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/images/shop/sale.jpg</value>
      <webElementGuid>da56416d-f7e4-46ff-b40c-4b53f2fccb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sale_image</value>
      <webElementGuid>1a52fbbc-e101-4c5f-9f89-b7dcd0abd236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Website for practice</value>
      <webElementGuid>458a0531-bb37-4d02-b448-28d99073f36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sale_image&quot;)</value>
      <webElementGuid>7e86d65f-48dc-4db2-8972-90dafec7ead4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='sale_image']</value>
      <webElementGuid>d7160771-2c29-4ad4-bc3d-44aad83b117b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='advertisement']/div/img</value>
      <webElementGuid>07854ea9-8eac-494b-b752-fa2a6a7b46d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Website for practice']</value>
      <webElementGuid>f0356e4c-d4e5-4cad-999a-fcc119ec72b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>371be8f0-9017-440d-a188-1ce247630930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/images/shop/sale.jpg' and @id = 'sale_image' and @alt = 'Website for practice']</value>
      <webElementGuid>f0c4393d-f051-416e-a4d8-269fc701e181</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
