<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Open a PROMPT box_debugTextbox</name>
   <tag></tag>
   <elementGuidId>6e53ada0-9ae7-40ba-b1f3-991c79414e45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='debugTextbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#debugTextbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bafa8397-ae10-43f0-83cc-949af74f68ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10ce44be-31f4-4ca8-b89e-684bfd1b6a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>debugTextbox</value>
      <webElementGuid>eb740873-021a-4518-be9a-a076a2c15260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;debugTextbox&quot;)</value>
      <webElementGuid>8d0880be-1630-44a6-9c4a-404bc8460c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='debugTextbox']</value>
      <webElementGuid>7d742db5-8664-436e-8f43-9a939f4b4d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>931285d8-9d7b-4445-b4d3-24e517f85cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'debugTextbox']</value>
      <webElementGuid>64f52f43-788e-4cd7-94f1-77657e790e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
