<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_LOGIN_addressInfoFrame</name>
   <tag></tag>
   <elementGuidId>a1f5c0ad-9516-435b-b775-0e154a1acbaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='addressInfoFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressInfoFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2bbbb5cf-696b-46d9-9ac3-9248678c1f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressInfoFrame</value>
      <webElementGuid>8e2f803e-ef46-4e26-b6cc-eea3ac585fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>learnks1-frame2.html</value>
      <webElementGuid>cca22116-6ec8-4680-a076-49cc5646cd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>43af15d1-713f-4550-942a-d28eda720e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>d9a50c5f-3411-493e-b83a-966a1b680e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>be225e7f35155a2414c89ebbd75b495a</value>
      <webElementGuid>c53d34a6-e4a1-45d6-8808-5629f9765b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressInfoFrame&quot;)</value>
      <webElementGuid>0cafd4ff-7793-48fb-b5c2-c8782b09ba51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='addressInfoFrame']</value>
      <webElementGuid>f1551ce2-01e0-421a-8cf2-d5cd94500626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/iframe</value>
      <webElementGuid>efbe60b3-379f-4adf-8320-138088bcc4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'addressInfoFrame' and @src = 'learnks1-frame2.html']</value>
      <webElementGuid>08339ccb-d8a0-4182-aea6-9774a5324bd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
