<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frame 2  Address_streetAddress</name>
   <tag></tag>
   <elementGuidId>cdb24123-5066-4371-8c76-8b9227546121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>18e25981-15a2-4f57-9a47-adbc6aeda89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;streetAddress&quot;)</value>
      <webElementGuid>01c0292c-6f02-4ebd-ac8f-26f025d03e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>streetAddress</value>
      <webElementGuid>5571bd85-5406-4689-9cb4-8e609fa80588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4784e2ce-ce98-45f2-bc7b-444321954e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/LearnKS/Page_Home/iframe_LOGIN_addressInfoFrame</value>
      <webElementGuid>57131514-e138-4440-b13d-a67d33d7c17b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
