<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frame 2  Address_postCode</name>
   <tag></tag>
   <elementGuidId>dd8cfa27-8763-4b9e-8b13-dc391c2a1902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postCode</value>
      <webElementGuid>ec227f2e-c1cf-431f-a0f1-e737de4667f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postCode&quot;)</value>
      <webElementGuid>126bd92a-7677-476b-bacd-6405a39753f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c484aa9-cef9-41d7-977c-044dbcfbc849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/LearnKS/Page_Home/iframe_LOGIN_addressInfoFrame</value>
      <webElementGuid>d910cc94-c84d-4861-a4ce-cb6400e05bfe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
