<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_LOGIN_personalInfoFrame</name>
   <tag></tag>
   <elementGuidId>a5612791-c78b-4ec4-8aec-4780ef8be374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='personalInfoFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personalInfoFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>402708f8-8518-4fbe-b657-c7e2dea40ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personalInfoFrame</value>
      <webElementGuid>e6f4d418-c95b-4b07-b91a-00945b929152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>learnks1-frame1.html</value>
      <webElementGuid>5a849585-15e3-4217-82e8-ee5e7e70cc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>881d06a9-a368-4da9-b765-d091eec1ccf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>125</value>
      <webElementGuid>e91deb74-e701-45d7-8710-ffd02a0fa334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personalInfoFrame&quot;)</value>
      <webElementGuid>600fb05e-3007-4470-8be0-9ea60c6530b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='personalInfoFrame']</value>
      <webElementGuid>749c4855-f355-4f1b-9d01-c81e29a06886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c54e4730-e358-46da-8914-3aedb488e688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'personalInfoFrame' and @src = 'learnks1-frame1.html']</value>
      <webElementGuid>bfa365ce-3cb2-4671-a731-e53b9bdea722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
